clean regex
killercup/sortStringToSql pull request #1
Opened 2017-04-28 20:49 UTC by caub

use strict not needed either

2017-04-28 20:51 UTC, caub commented
@killercup Thanks for that module, can I ask you why 'id' is not simply 'id' instead of 'id ASC NULLS LAST'. Why not omitting ASC and NULL LAST default values?

2017-05-02 16:04 UTC, killercup commented
Thanks, but I'd rather keep the code very explicit. :) That's also the reason why it generates the full form for a simple `id`.

> Also is it really injection-safe?

I think so? The regex is very specific in allowing alphanumerical characters and dots only (aside from the plus/minus pre/suffix), so it'd be interesting to see if you can break SQL based on that…

Anyway, I haven't tested it or anything, nor even thought about it, as this was just for a internal prototype and didn't go to production or anything.

2017-05-02 16:06 UTC, killercup commented
Oh, you can have it generate invalid SQL, of course, using something like `+foo......bar`. But you can supply invalid column names anyway, so it's not really a hack.

2017-05-02 16:20 UTC, caub commented
Ok, well I plan to use it, I just wanted to improve the regex (it's clearer and standard to use `?`), the `use strict` are not necessary and that's it. Would be glad if you explain what's part annoys you

2017-05-02 16:27 UTC, killercup requested changes
Okay, the `?` regex is totally fine, and getting rid of `use strict` is probably fine in 2017 as well. Removing the `field` var just makes it harder to read, though.

2017-05-02 16:27 UTC, killercup commented on index.js
> +  return parsed[2] + order + nulls;
This really just makes it harder to read (I'm also quite sure it doesn't matter for performance)

2017-05-02 16:37 UTC, killercup commented
Thanks for your interest and wanting to help out here, by the way :)

> I think it would be better without the defaults NULL LAST and ASC, but I respect your respect your choice there

Cool. It's just that adding code to make things less explicit is not a good trade-off to me :)

Btw, What database driver are you using? Maybe it'd be a good idea to not just have this emit strings but rather an array of orderings? It might also be a good idea to not just silently ignore fields that don't match the regex.

To be honest, I really have no use case for this anymore, and if you want to, I could absolutely transfer the repo as well as the npm package to you. This way you don't have to wait for me and this package gets some more love :)

2017-05-02 16:43 UTC, caub commented
updated

I use [pg](https://github.com/brianc/node-postgres/) module, and a string as input is good, because it would come like that from an api call `&sort=-updated`

2017-05-02 16:44 UTC, killercup approved these changes

2017-05-02 16:44 UTC, merged

2017-05-02 16:45 UTC, killercup commented
Thanks & merged! Just let me know if you want to maintain this package :)

2017-05-02 16:48 UTC, caub commented
ok no problem, as you wish

2017-05-02 16:53 UTC, killercup commented
You now have contributor rights on github and npm 👍